### ISSUE TITLE
App warns at startup and crashes if one tries to create a todo

### ISSUE THREAD

**Issue by Sanva** [kevinresol/examples-react-native#4]
I've tried building for Android and it builds, but the app shows a warning on startup and if you try for example to add a new todo it crashes.

Build steps:

1. lix download
2. haxe android.hxml
3. cd bin
4. yarn
5. yarn exec react-native run-android

The application start as expected in the emulator, but the following warning appears just at startup: *Warning, can't call `setState` on a component that is not yet mounted. This is a no-op, [...]*.

And if you try to create a new todo, it crashes when pressing *Enter*:

![Screenshot_1553865190](https://user-images.githubusercontent.com/911204/55235067-dc535c00-522c-11e9-8e13-74ef8296db79.png)

**Comment by kevinresol** [comment]
Hmmm I can add TODO fine... (though the yellow box is there for me too)

Anyway I just pushed some updates which seems to get rid of the yellow box, see if that helps?

**Comment by Sanva** [comment]
Now it is worse, the app crashes just at startup:

![Screenshot_1553954965](https://user-images.githubusercontent.com/911204/55277218-d4afb800-52fd-11e9-831e-d4fec6bae41f.png)

The line 1813 in `main.js` is this one:

```
Object.defineProperty(attr,"__cct",{ value : actual, enumerable : false});
```

Maybe something related to Android version? I'm using the emulator with Nexus 5X API 28 x86.

**Comment by kevinresol** [comment]
I remember this happening, this is related to the react devtools. @back2dos any ideas?

**Comment by back2dos** [comment]
That's probably this: https://github.com/MVCoconut/coconut.react-core/issues/7

Can you try a prod version of react?

**Comment by Sanva** [comment]
> Can you try a prod version of react?

OK, I'll try that.

But, the thing is... why I'm not getting the same results as @kevinresol ? I'm using exactly the same repository so... is the build process pulling something from my system?

**Comment by back2dos** [comment]
Hmm, maybe it's an environment difference? There's some `node_env` variable that can be `production` or `development` that sometimes affects how things are built. 

Otherwise, can you check if putting `untyped Object.freeze = Object.seal = function () {}` right into the main function sidesteps the problem?

**Comment by Sanva** [comment]
> Hmm, maybe it's an environment difference? There's some node_env variable [...]

Checked it and looks like it's not the case.

> Otherwise, can you check if putting [...]

Yes, that works. It also works if you comment this line → https://github.com/MVCoconut/examples-react-native/blob/master/build.hxml#L7 ( `-D react_devtools` ).

Close this if you want — not doing it myself since this could be useful for someone until fix of coconut.react-core#7 .

**Comment by back2dos** [comment]
Closing, as the other issue is still around.
