### ISSUE TITLE
Can't compile with Haxe 4.0.0-rc.2

### ISSUE THREAD

**Issue by neelts** [kevinresol/examples-react-native#5]
File "_build/src/macro/eval/evalContext.ml", line 342, characters 2-8: Assertion failed

**Comment by kevinresol** [comment]
Please use nightly. rc2 is known to be buggy. See https://github.com/HaxeFoundation/haxe/issues/8039

**Comment by neelts** [comment]
Thank you! Also with nighly (89d6961) I'm getting this error: 
react-next/1.108.0/github/beb37e8a94b46e1d42180fbd179a0eede40e3047/src/lib/react/jsx/HtmlEntities.hx:4: character 63 : Invalid escape sequence
\u. UTF-16 surrogates are not allowed in strings.

**Comment by neelts** [comment]
But fine with nightly 4e36cd6
